//
//  Natruc.swift
//  natruc
//
//  Created by Jiri Dutkevic on 05/07/15.
//  Copyright (c) 2015 Jiri Dutkevic. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Natruc : NSObject {

    //// Cache

    private struct Cache {
        static var white: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static var foregroundGray: UIColor = UIColor(red: 0.678, green: 0.678, blue: 0.678, alpha: 1.000)
        static var black: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        static var foregroundBlue: UIColor = UIColor(red: 0.447, green: 0.545, blue: 0.745, alpha: 1.000)
        static var backgroundBlue: UIColor = UIColor(red: 0.090, green: 0.251, blue: 0.580, alpha: 1.000)
        static var lightBlue: UIColor = UIColor(red: 0.024, green: 0.192, blue: 0.306, alpha: 1.000)
        static var lightRed: UIColor = UIColor(red: 0.733, green: 0.082, blue: 0.118, alpha: 1.000)
        static var lightGreen: UIColor = UIColor(red: 0.024, green: 0.314, blue: 0.235, alpha: 1.000)
        static var yellow: UIColor = UIColor(red: 0.980, green: 0.773, blue: 0.122, alpha: 1.000)
        static var darkBlue: UIColor = UIColor(red: 0.012, green: 0.118, blue: 0.188, alpha: 1.000)
        static var darkRed: UIColor = UIColor(red: 0.455, green: 0.051, blue: 0.071, alpha: 1.000)
        static var darkGreen: UIColor = UIColor(red: 0.012, green: 0.192, blue: 0.145, alpha: 1.000)
        static var backgroundGray: UIColor = UIColor(red: 0.847, green: 0.847, blue: 0.847, alpha: 1.000)
    }

    //// Colors

    public class var white: UIColor { return Cache.white }
    public class var foregroundGray: UIColor { return Cache.foregroundGray }
    public class var black: UIColor { return Cache.black }
    public class var foregroundBlue: UIColor { return Cache.foregroundBlue }
    public class var backgroundBlue: UIColor { return Cache.backgroundBlue }
    public class var lightBlue: UIColor { return Cache.lightBlue }
    public class var lightRed: UIColor { return Cache.lightRed }
    public class var lightGreen: UIColor { return Cache.lightGreen }
    public class var yellow: UIColor { return Cache.yellow }
    public class var darkBlue: UIColor { return Cache.darkBlue }
    public class var darkRed: UIColor { return Cache.darkRed }
    public class var darkGreen: UIColor { return Cache.darkGreen }
    public class var backgroundGray: UIColor { return Cache.backgroundGray }

}

@objc protocol StyleKitSettableImage {
    func setImage(image: UIImage!)
}

@objc protocol StyleKitSettableSelectedImage {
    func setSelectedImage(image: UIImage!)
}
