//
//  Natruc.swift
//  natruc
//
//  Created by Jiri Dutkevic on 06/07/16.
//  Copyright (c) 2016 Jiri Dutkevic. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import UIKit

public class Natruc : NSObject {

    //// Cache

    private struct Cache {
        static let white: UIColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        static let foregroundGray: UIColor = UIColor(red: 0.588, green: 0.557, blue: 0.482, alpha: 1.000)
        static let black: UIColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        static let foregroundBlue: UIColor = UIColor(red: 0.451, green: 0.612, blue: 0.596, alpha: 1.000)
        static let backgroundBlue: UIColor = UIColor(red:0.69, green:0.87, blue:0.98, alpha:1.0)
        static let lightBlue: UIColor = UIColor(red: 0.475, green: 0.584, blue: 0.180, alpha: 1.000)
        static let lightRed: UIColor = UIColor(red: 0.671, green: 0.122, blue: 0.118, alpha: 1.000)
        static let lightGreen: UIColor = UIColor(red: 0.310, green: 0.404, blue: 0.412, alpha: 1.000)
        static let yellow: UIColor = UIColor(red: 0.996, green: 0.929, blue: 0.000, alpha: 1.000)
        static let darkBlue: UIColor = UIColor(red: 0.294, green: 0.361, blue: 0.110, alpha: 1.000)
        static let darkRed: UIColor = UIColor(red: 0.416, green: 0.075, blue: 0.071, alpha: 1.000)
        static let darkGreen: UIColor = UIColor(red: 0.192, green: 0.251, blue: 0.255, alpha: 1.000)
        static let backgroundGray: UIColor = UIColor(red: 0.980, green: 0.929, blue: 0.804, alpha: 1.000)
        static let activeGray: UIColor = UIColor(red: 0.196, green: 0.184, blue: 0.161, alpha: 1.000)
        static let sectionHeader: UIColor = UIColor(red:0.03, green:0.61, blue:0.85, alpha:1.0)
        static let infoFooterBackground: UIColor = UIColor(red:0.00, green:0.29, blue:0.58, alpha:1.0)
        static let red: UIColor = UIColor(red:0.80, green:0.09, blue:0.10, alpha:1.0)
    }

    //// Colors

    public class var white: UIColor { return Cache.white }
    public class var foregroundGray: UIColor { return Cache.foregroundGray }
    public class var black: UIColor { return Cache.black }
    public class var foregroundBlue: UIColor { return Cache.foregroundBlue }
    public class var backgroundBlue: UIColor { return Cache.backgroundBlue }
    public class var lightBlue: UIColor { return Cache.lightBlue }
    public class var lightRed: UIColor { return Cache.lightRed }
    public class var lightGreen: UIColor { return Cache.lightGreen }
    public class var yellow: UIColor { return Cache.yellow }
    public class var darkBlue: UIColor { return Cache.darkBlue }
    public class var darkRed: UIColor { return Cache.darkRed }
    public class var darkGreen: UIColor { return Cache.darkGreen }
    public class var backgroundGray: UIColor { return Cache.backgroundGray }
    public class var activeGray: UIColor { return Cache.activeGray }
    public class var sectionHeader: UIColor { return Cache.sectionHeader }
    public class var infoFooterBackground: UIColor { return Cache.infoFooterBackground }
    public class var red: UIColor { return Cache.red }

}
